In [4]:
import numpy as np
#vektor
v_baris = np.array([1,2,3])
v_kolom = np.array([[1],
                   [2],
                   [3]])
print("Vektor Baris: \n",v_baris)
print("vektor Kolom: \n",v_kolom)

#matrik
matrik = np.array([[1,2],[1,2],[1,2]])
print("Matrik: \n",matrik)

Vektor Baris: 
 [1 2 3]
vektor Kolom: 
 [[1]
 [2]
 [3]]
Matrik: 
 [[1 2]
 [1 2]
 [1 2]]


In [7]:
import numpy as np
v_baris = np.array([1,2,3])
v_kolom = np.array([[1,2],[1,2],[1,2]])
print(v_baris.ndim)
print(v_kolom.ndim)
print(v_kolom.shape)

1
2
(3, 2)


In [9]:
import numpy as np
from scipy import sparse

matrik = np.array([[0,0],[0,1],[3,0]])
matrik_sparse = sparse.csr_matrix(matrik)
print(matrik_sparse)

  (1, 1)	1
  (2, 0)	3


In [12]:
import numpy as np
matrik = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
print("Matrik: ",matrik)
print("Jumlah baris dan kolom: ",matrik.shape)
print("Jumlah elemen matrik (baris * kolom): ",matrik.size)
print("Jumlah dimensi matrik: ",matrik.ndim)

Matrik:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Jumlah baris dan kolom:  (3, 4)
Jumlah elemen matrik (baris * kolom):  12
Jumlah dimensi matrik:  2


In [27]:
import numpy as np
vector = np.array([1,2,3,4,5,6])
matrik = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

#print(vector[:])
#print(vector[:5])
#print(vector[3:])
#print(vector[-3])
print(matrik[:2,1:2])

[[2]
 [5]]


In [34]:
import numpy as np

matrik = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

add_100 = lambda i: i + 100
vectorisasi_tambah_100 = np.vectorize(add_100)
#print(vectorisasi_tambah_100(matrik))
#print(matrik+100)

#print(np.max(matrik))
#print(np.min(matrik))

#print(np.max(matrik,axis=0))
#print(np.max(matrik,axis=1))
print(np.mean(matrik))
print(np.var(matrik))
print(np.std(matrik))

print(np.mean(matrik,axis=0))

5.0
6.666666666666667
2.581988897471611
[4. 5. 6.]


In [16]:
import numpy as np
matrik = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
#print(matrik.reshape(2,6))

#print(matrik.T)

#print(np.array([1,2,3,4,5,6,7,8]).T)
#np.array([[1,2,3,4,5,6,7,8]]).T

print(matrik.flatten())
print(matrik.reshape(1,-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [19]:
import numpy as np
v_a = np.array([1,2,3])
v_b = np.array([4,5,6])
#v_a @ v_b
np.dot(v_a,v_b)

32

In [27]:
import numpy as np
matrik_a = np.array([[1,1,1],
                     [1,1,1],
                     [1,1,1]])
matrik_b = np.array([[1,3,1],
                     [1,3,1],
                     [1,3,8]])
#print(matrik_a + matrik_b)
#print(np.add(matrik_a,matrik_b))
#np.subtract(matrik_a,matrik_b)

matrik_1 = np.array([[1,1],
                     [1,2]])
matrik_2 = np.array([[1,3],
                     [1,2]])
np.dot(matrik_1,matrik_2)

array([[2, 5],
       [3, 7]])